name: Workflow
on:
  push:
  
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4
     
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '17'
          distribution: 'temurin' 
     
      - name: Build
        run: | 
          chmod 777 gradlew
          ./gradlew build

    
